name: flutter_timer
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  bloc:
  build_runner:  
  cherrypick: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc:
  shared_preferences: ^0.5.6

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1


flutter:
  uses-material-design: true
